### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ysupreme12** [indilo53/gtautil#2]
In powershell I get an error:
gta : The term 'gta' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
pelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ gta util find --position 441,-983,30
+ ~~~
    + CategoryInfo          : ObjectNotFound: (gta:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by indilo53** [comment]
dont put space in gtautil
