### ISSUE TITLE
Added hairstyles passes through helmets and caps

### ISSUE THREAD

**Issue by KoRnBoy82** [indilo53/gtautil#22]
Hairstyles added with gtautil passes through helmets and hats.

![image](https://user-images.githubusercontent.com/22198808/118315974-36264700-b4c4-11eb-9f70-32bfac6eeb1a.png)

**Comment by sadoj-kuro** [comment]
same here, gtautil is dead project......

**Comment by KoRnBoy82** [comment]
Anyway after checking it's not gtautil fault. It's the haircut's fault. There is a fix for that we need to do.

**Comment by KuroSenseii** [comment]
> Anyway after checking it's not gtautil fault. It's the haircut's fault. There is a fix for that we need to do.

Et quand pensez vous corriger ce probleme ou si vous pouvez expliquer la correction.
