### ISSUE TITLE
[FiveM] Addon vehicles .yft and .ytd files corrupted "address is neither virtual nor physical"

### ISSUE THREAD

**Issue by Sim0nePL** [indilo53/gtautil#37]
So, hi.
I used this tool to auto generate resources for FiveM server from GTA V .rpf files like addon cars.
When I extracted addon car's "dlc.rpf" archive via this tool and make FiveM car resource from those files, car crashes client when spawned, giving this error. 

![image](https://github.com/indilo53/gtautil/assets/85204348/23c07350-7b74-4822-81ca-ef365a31ae3b)
![error](https://github.com/indilo53/gtautil/assets/85204348/a249d116-152c-4982-bb90-dc8626f3db1a)

In contrast that doesn't happened when I used OpenIV to extract car archive and make resource in this same way. So I decided to see what's different between these files. I picked first two files, one from OpenIV extraction and second from GTAUtil extraction and compare them in HxD, so I can see differences between them.
And this is what I saw at first pair of files ( car.yft ):
![f8t yft](https://github.com/indilo53/gtautil/assets/85204348/c7dfb764-9650-43ee-95ed-bcbf6919e437)
And second pair of files: ( car.ytd ): 
![f8t ytd](https://github.com/indilo53/gtautil/assets/85204348/07d9337f-22fc-47ab-8a40-b6c5b527f29b)

In each of these pair fourth byte is corrupted. GTAUtil pass there 7, when desired is 37.
When I changed this single byte in each of files in stream folder, everything works as well and car is loading correctly.

**Comment by indilo53** [comment]
Thanks for detailled walktrough :)

I updated my new repo at [https://github.com/gizzdev/gtautil](https://github.com/gizzdev/gtautil)

In fact I just recompiled GTAUtil with the modification I made in GTA Toolkit after your post : [59082b8e9e55a9cbbb17e069177d476ffde4a0c7](https://github.com/gizzdev/gta-toolkit/commit/59082b8e9e55a9cbbb17e069177d476ffde4a0c7)

I did not tested it but it should work as expected now

**Comment by Sim0nePL** [comment]
Thanks.
Everything works.
