### ISSUE TITLE
Naming is being ordered incorrect.

### ISSUE THREAD

**Issue by PERPGamer** [indilo53/gtautil#4]
So after hours of thinking, I did something wrong I figured out that the way the names are sorted and then complied is wrong. 
The program is ordering them like this: https://media.discordapp.net/attachments/571850097260888075/593145245059776512/unknown.png
Instead of this:
https://media.discordapp.net/attachments/571850097260888075/593145310575067140/unknown.png
Which is why the models to numbers are mismatched 

NOTE: I know the program I am using in the pictures is not this but I am just using it to show you what it is doing. I know this due to checking the output of GTAutil vs. the program about renaming, the first picture is what GTAUTIL is doing rn.

**Comment by indilo53** [comment]
Should be fixed now

**Comment by PERPGamer** [comment]
Yep, thanks :) Can't wait until the Hats are fixed too :)

**Comment by indilo53** [comment]
Please tell me if it works for you so I can close the issue

**Comment by PERPGamer** [comment]
Yep it's fixed
