### ISSUE TITLE
Implement DeleteFile in RageArchiveWrapper7

### ISSUE THREAD

**Issue by TechInterMezzo** [indilo53/gtautil#5]
I am using your fork of gta-toolkit.
Would it be possible to implement the function to delete files in archives?
At the moment it throws a NotImplementedException.

https://github.com/indilo53/gta-toolkit/blob/master/RageLib.GTA5/ArchiveWrappers/RageArchiveWrapper7.cs#L536

**Comment by indilo53** [comment]
Done :) keep in mind there is no defragmenting here so file will keep the same size
