### ISSUE TITLE
FiveM: Resource Deletes Native Hats & Matching wrong .ydd file with .ytd

### ISSUE THREAD

**Issue by nejccifer** [indilo53/gtautil#6]
**BUG 1: Resource Deletes All Native Hats That Aren't In mp_m_freemode_01 DLC**

Essentially what happens is after I start streaming all my addon-clothes, all of them work perfectly fine and reserved slots are working correctly too, however what happens is that 90% of all native in-game hats that should be there from complete beggining are missing (all hats that should be there after the reserved spaces end). Once I try to put them on, nothing happens, just like if you try to select reserved slot (no hat).

The reason why I know that addon streaming is causing it, is because if I try to go in the server without starting the resource for addon clothing, all the previously missing hats are there.

~**BUG 2: Mathing Wrong .ydd with .ytd**~

~After some further testing and trying, I also found out that once I go above number 10 in .ydd files, and try to compile entire thing for FiveM, the gtautil software start putting wrong .ydd files wrong textures.
For Example:~

~In source folder I have:~

~0/0.ytd, 1.ytd, 2.ytd~
~0.ydd~
~. . .~
~9/0.ytd              (Folder with files)~
~10/0.ytd, 1.ytd      (Folder with files)~
~9.ydd~
~10.ydd~

~Once I compile this, it starts putting all the .ydd files from number 1 till the very last one with wrong .ytd textures. I haven't found any pattern yet on how it choses, however not one model has the correct texture (Example: 9.ydd is matched with textures from folder 3, 2.ydd is matched with folder 8, etc...).~

**UPDATE:**
Second bug with matching wrong .ydd files occured because I was on the wrong version of gtautil. I was using 2.2.2.0, while the newest version with fix was 2.2.2.5.

However now I'm experiencing a new bug (Honestly, can't they just leave me alone already xD), where my ped's hair is literally sticking out of the hat.
![20190708104205_1](https://user-images.githubusercontent.com/16784435/60796230-53be5300-a16d-11e9-90f7-79d1b89922d6.jpg)

**INFO:**

**GTAUTIL Version:** 2.2.2.5
**Windows Version (not sure if it's relavante):** Windows 10

**Comment by indilo53** [comment]
Hello, is this a custom hat in the picture ?

**Comment by nejccifer** [comment]
Yes. Native hats work completly fine, however this happens with all custom hats

**Comment by indilo53** [comment]
Yes its because I have yet to figure out how to handle this, its a known bug.

For the slot problem can you try with less slots or without reserving slots at all and give me the result ? I don't have FiveM license to test.

**Comment by nejccifer** [comment]
Okay, I'll try later today, as I'm not home now and I'll report back to you

**Comment by nejccifer** [comment]
Hello, I did some testing and this are the results:

**No Reserved Slots:** All Hats Accessible
**100 Reserved Slots:** All Hats Accessible
**200 Reserved Slots:** Hats That Aren't From mp_m_freemode_01 Aren't Shown

If it will help you, I can say that if I remember correctly, when I was compiling clothes with version 2.2.2.0 all the hats were accessible, even if I had 200 reserved slots or even more. This bug of hats not appearing appeared when I upgraded from 2.2.2.0 to 2.2.2.5

**Comment by indilo53** [comment]
Reading your first comment, the issus was happening even in 2.2.2.0 only way to confirm is to try with this version and report back result

**Comment by indilo53** [comment]
But in my very first tests I already saw that a too high number of reserved props / components will fail

**Comment by nejccifer** [comment]
Oh yeah, srry I wrote it wrong. What I wanted to say is that hats worked normally in 2.2.2.0, meaning the hair wasn't sticking out of them, so something must have changed in the meantime that caused the hair to not properly collide with hat. What I'll do right now is just lower reserved slots for props and wait until bug fix for hats is released. 

Thank you for your help ^^

**Comment by sadoj-kuro** [comment]
same here, but with all version dont work native hat is missing. i have trying to put reserbvedprop to 100

gtautil genpeddefs --input pedproject --output build --reserve 200 --reserveprops 100 --fivem
